### ISSUE TITLE
access rights ???

### ISSUE THREAD

**Issue by flik** [werein/gallery#1]
Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@bitbucket.org:werein/ckeditor-outsourced.git' "/var/lib/gems/1.9.1/cache/bundler/git/ckeditor-outsourced-34c43947998654e0e55297e33dc879476c4fd87f" --bare --no-hardlinks --quiet due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@bitbucket.org:werein/ckeditor-outsourced.git' "/var/lib/gems/1.9.1/cache/bundler/git/ckeditor-outsourced-34c43947998654e0e55297e33dc879476c4fd87f" --bare --no-hardlinks --quiet` in directory /home/flik/www/gallery has failed.
Warning: Permanently added the RSA host key for IP address '131.103.20.168' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone 'git@bitbucket.org:werein/ckeditor-outsourced.git' "/var/lib/gems/1.9.1/cache/bundler/git/ckeditor-outsourced-34c43947998654e0e55297e33dc879476c4fd87f" --bare --no-hardlinks --quiet due to error (3/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@bitbucket.org:werein/ckeditor-outsourced.git' "/var/lib/gems/1.9.1/cache/bundler/git/ckeditor-outsourced-34c43947998654e0e55297e33dc879476c4fd87f" --bare --no-hardlinks --quiet` in directory /home/flik/www/gallery has failed.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone 'git@bitbucket.org:werein/ckeditor-outsourced.git'
"/var/lib/gems/1.9.1/cache/bundler/git/ckeditor-outsourced-34c43947998654e0e55297e33dc879476c4fd87f" --bare --no-hardlinks --quiet`
in directory /home/flik/www/gallery has failed.

**Comment by jirikolarik** [comment]
Hi, it's using wrong (old) repository.. now it's stored on github: `werein/ckeditor-outsourced` or even on ruby gems as `creditor-outsourced`, I'll try to remove this dependency as soon as I can

**Comment by flik** [comment]
thanks :)
